version: '3.9'

services:
    wg-rtorrent:
      container_name: wg-rtorrent
      build: .
      volumes:
        - pia:/pia
        - pia-shared:/pia-shared
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
          LOC: ca_ontario
          USER: p8765976
          PASS: 9SffoF7puX
          PORT_FORWARDING: 1
          PUID: ${USERID}
          PGID: ${USERID}
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.default.disable_ipv6=1
        - net.ipv6.conf.all.disable_ipv6=1
        - net.ipv6.conf.lo.disable_ipv6=1
      healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 30s
        timeout: 10s
        retries: 3

volumes:
    pia:
    pia-shared:
