#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export WEBUI_PORT=${WEBUI_PORT:-8080}

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -s 10000 -c "ping -c 1 google.ca" \
        s6-setuidgid root /scripts/run
